### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by linxOD** [fun-with-editions/akademie-static#1]
- [x] setup actions workflow to fetch data
  - [x]  fetch_data.sh -> do not check in the data to this repo
  - [x]  included in github action -> create a CI|CD workflow to fetch->transform->publish the app
  - [x] #2 
  - [x] #3 
  - [x] #4 
  - [x] #5 
  - [x] #6 
- [x] create typesense search
  - [x] #7
  - [x] #8
  - [x] #9
  - [x] #10
- [x] update cookiecutter HTML templates (XSL transformations)
  - [x] #11
  - [x] #12
  - [x] #13
  - [x] #14 
- [x] create edition detail pages
  - [x] #15
    - [x] #16
  - [x] #17
    - [x] #18
    - [x] #19
    - [x] #20
- [x] #21
